apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: surf-and-sell
build:
  artifacts:
  - image: surf-and-sell
deploy:
  kubectl:
    manifests:
    - k8s/surf-and-sell.yaml
portForward:
- resourceType: deployment
  resourceName: surf-and-sell
  port: 7922
  localPort: 7922
    manifests:
    - k8s/deployment.yaml
portForward:
- resourceType: deployment
  resourceName: surf-and-sell
  port: 7922
  localPort: 7922